---
- hash: "1156f7416b4467e445a3d0427cd839be4eea3d23"
  entry:
    text: "The register of places in the UK with a postal address. Some addresses\
      \ have a geographical location.\n"
    fields:
    - "address"
    - "property"
    - "street"
    - "locality"
    - "town"
    - "area"
    - "postcode"
    - "country"
    - "latitude"
    - "longitude"
    register: "address"
    registry: "ordnance-survey"
    copyright: "Contains Ordnance Survey data © Crown copyright & database right 2015\n\
      Contains National Statistics data © Crown copyright & database right 2015\n\
      Contains Royal Mail data © Royal Mail copyright & database right 2015\n"
  last-updated: "2015-09-24T16:11:36.526Z"
- hash: "b5722c61950ba170f99c5143fd1feac3bc5094dd"
  entry:
    fields:
    - "charity"
    - "name"
    - "company"
    - "start-date"
    - "end-date"
    register: "charity"
    registry: "charity-commission"
    text: "The register of UK charities.\n"
  last-updated: "2015-09-24T16:11:36.885Z"
- hash: "05e82a8fac07937e55571a1a8088276e2680d14e"
  entry:
    text: "The register of [Foreign & Commonwealth Office](https://www.gov.uk/government/organisations/foreign-commonwealth-office)\
      \ list of approved British English-language names and descriptive terms for\
      \ [countries](http://country.openregister.org) and territories of the world\
      \ and their citizens.\n"
    fields:
    - "country"
    - "name"
    - "official-name"
    - "citizen-names"
    - "start-date"
    - "end-date"
    - "text"
    register: "country"
    registry: "foreign-commonwealth-office"
  last-updated: "2015-09-24T16:11:37.290Z"
- hash: "e3185a82503621f80e8ed60891dbbcd52764cc1a"
  entry:
    text: "This register of datatypes constraining a field value and idenitifying\
      \ ways in which it may be encoded a representation.\n"
    fields:
    - "datatype"
    - "text"
    register: "datatype"
    registry: "cabinet-office"
  last-updated: "2015-09-24T16:11:37.464Z"
- hash: "e56d6a9f676ae012b64bda234757ea78bb68fd38"
  entry:
    text: "The register of field names which may appear in a register.\n"
    fields:
    - "field"
    - "datatype"
    - "register"
    - "cardinality"
    - "text"
    register: "field"
    registry: "cabinet-office"
  last-updated: "2015-09-24T16:11:37.683Z"
- hash: "0eb33ca1349167da65b114dbe0880343c9461695"
  entry:
    fields:
    - "food-hygiene"
    - "rating"
    - "company"
    - "name"
    - "date-of-rating"
    - "address"
    register: "food-hygiene"
    registry: "food-standards-agency"
    text: "The register of [Food Standards Agency](http://www.food.gov.uk/) hygiene\
      \ inspection ratings.\n"
- hash: "1e5b3697a1e43a13a707d76ac079b98dea05393f"
  entry:
    text: "The register of [Post towns](http://en.wikipedia.org/wiki/Post_town) which\
      \ may appear in postal [addresses](http://address.openregister.org) in the UK.\n"
    fields:
    - "post-town"
    - "start-date"
    - "end-date"
    - "text"
    register: "post-town"
    registry: "cabinet-office"
  last-updated: "2015-09-24T16:11:39.051Z"
- hash: "0fc4b18d1d8bae695b69bd36e1c9d6589d53247f"
  entry:
    text: "The register of UK Postal codes which may appear in an [address](http://address.openregister.org).\n"
    fields:
    - "postcode"
    - "latitude"
    - "longitude"
    register: "postcode"
    registry: "office-for-national-statistics"
    copyright: "Contains Ordnance Survey data © Crown copyright & database right 2015\
      \  \nContains National Statistics data © Crown copyright & database right 2015\
      \  \nContains Royal Mail data © Royal Mail copyright & database right 2015 \
      \ \n"
  last-updated: "2015-09-24T16:11:39.167Z"
- hash: "45dd2b4e94cfffbf66bbe8f2eb6307d04f8153d4"
  entry:
    text: "The register of UK Ministerial Departments, agencies and public bodies\
      \ sponsored by the UK government.\n"
    fields:
    - "public-body"
    - "name"
    - "website"
    - "public-body-type"
    - "parent-bodies"
    - "text"
    - "crest"
    - "official-colour"
    register: "public-body"
    registry: "cabinet-office"
  last-updated: "2015-09-24T16:11:40.937Z"
- hash: "a8311d6acc8f3d70bd43f99348ab036f1bac8e66"
  entry:
    text: "The register of UK government registers.\n"
    fields:
    - "register"
    - "text"
    - "registry"
    - "copyright"
    - "fields"
    register: "register"
    registry: "cabinet-office"
  last-updated: "2015-09-24T16:11:41.813Z"
- hash: "524839933bb3b60fac4d3e42acdcb3a7ed636e1d"
  entry:
    fields:
    - "school"
    - "name"
    - "start-date"
    - "end-date"
    - "gender"
    - "religious-character"
    - "minimum-age"
    - "maximum-age"
    - "headteacher"
    - "website"
    - "address"
    register: "school"
    registry: "department-for-education"
    text: "The register of primary, secondary and\_special needs schools in England\
      \ and Wales.\n"
  last-updated: "2015-09-24T16:11:42.291Z"
- hash: "8857b487152b88c99b30b6eee397c44237df99e9"
  entry:
    text: "The register of UK Government domain names.\n"
    fields:
    - "government-domain"
    - "owner"
    - "end-date"
    register: "government-domain"
    registry: "government-digital-service"
  last-updated: "2015-09-30T10:20:13.741Z"
- hash: "cf82ce7c04feb365e42e37487cff33f42c39c42b"
  entry:
    fields:
    - "industry"
    - "name"
    - "start-date"
    - "end-date"
    register: "industry"
    registry: "office-for-national-statistics"
    text: "Standard industry codes."
- hash: "6ee905ccce93d1abe6a59b58bfdd93006db763a0"
  entry:
    fields:
    - "local-authority"
    - "name"
    - "website"
    - "email"
    - "address"
    - "start-date"
    - "end-date"
    register: "local-authority"
    registry: "department-for-communities-and-local-government"
    text: "The register of local authorities."
- hash: "785f2592364ebb5decbfa775aebeab6688ad00ee"
  entry:
    fields:
    - "food-premises-rating"
    - "food-premises"
    - "food-premises-rating-value"
    - "food-premises-rating-hygiene-score"
    - "food-premises-rating-structural-score"
    - "food-premises-rating-confidence-in-management-score"
    - "local-authority"
    - "food-premises-rating-reply"
    - "start-date"
    - "inspector"
    - "end-date"
    register: "food-premises-rating"
    registry: "food-standards-agency"
    text: "The register of hygiene inspection ratings for food premises."
- hash: "8947a075df13938716c42c08406734346a538b0e"
  entry:
    fields:
    - "food-premises-type"
    - "name"
    register: "food-premises-type"
    registry: "food-standards-agency"
    text: "Types of food premises."
- hash: "84db49e0418dfb512ea762d18059c27bff63ddf8"
  entry:
    fields:
    - "food-premises"
    - "name"
    - "business"
    - "food-premises-types"
    - "local-authority"
    - "premises"
    - "start-date"
    - "end-date"
    register: "food-premises"
    registry: "food-standards-agency"
    text: "The register of food premises."
- hash: "2adff322e8ef2340e984164adeee15706ee412ad"
  entry:
    fields:
    - "company"
    - "name"
    - "company-status"
    - "registered-office"
    - "industry"
    - "start-date"
    - "end-date"
    register: "company"
    registry: "companies-house"
    text: "The register of UK companies.\n"
- hash: "4c31dfb6e889cd0f9fc66964d052fb9554174d1e"
  entry:
    fields:
    - "premises"
    - "address"
    - "start-date"
    - "end-date"
    register: "premises"
    registry: "valuation-office-agency"
    text: "The register of business premises."
- hash: "b6a1abf17b1405fe2eaa917dfa8f9bf22d2d3dc9"
  entry:
    fields:
    - "location"
    - "point"
    register: "location"
    registry: "cabinet-office"
    text: "Geographic locations of places found in government data which may be published\
      \ under an open government licence"
