sudo: false
language: java
jdk:
  - oraclejdk8
services:
  - rabbitmq
addons:
  postgresql: "9.4"
cache:
  directories:
    - '$HOME/.gradle/caches'
    - '$HOME/.gradle/wrapper'
before_script:
  - psql -c 'create database test_mint;' -U postgres
  - psql -c 'create database ft_mint;' -U postgres
script:
  - ./gradlew clean build